[package]
name = "gpclient"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpcommon = { path = "../gpcommon" }
tokio = { version = "1.0", features = ["full"] }
